In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv("clean_data.csv")

In [3]:
data.head(5)

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId  rating  Totalratingcount  
0       3     4.0               241  
1       6     5.0               241  
2       8     4.0               241  
3      10     4.0               241  
4      11     4.5               241

In [4]:
data['title']

0                   Toy Story (1995)
1                   Toy Story (1995)
2                   Toy Story (1995)
3                   Toy Story (1995)
4                   Toy Story (1995)
                    ...             
99995           The Interview (2014)
99996    Fifty Shades of Grey (2015)
99997    Fifty Shades of Grey (2015)
99998               Wild Card (2015)
99999          Boy Meets Girl (2015)
Name: title, Length: 100000, dtype: object

In [5]:
len(set(data['title']))

8225

duplicate values

In [6]:
pivot_table=data.pivot_table(index='title',columns='userId',values='rating').fillna(0)

In [7]:
pivot_table

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  0.0  0.0  0.0  2.0   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  ...  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  ...  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  ...  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  ...  0.0  4.0  0.0   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'burbs, The (1989)                       0.0  0.0  0.0  0.0  3.5  0.0  0.0  
...                                      ...  ...  ...  ...  ...  ...  ...  
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0  
¡Three Amigos! (1986)                    3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8225 rows x 702 columns]

In [8]:
from scipy.sparse import csr_matrix

In [9]:
pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
feature_matrix=csr_matrix(pivot_table.values)

csr_matrix stores matrix in form of compressed row format

from sklearn.neighbors import KNearestNeighbors

In [11]:
from sklearn.neighbors import NearestNeighbors

In [12]:
model=NearestNeighbors(algorithm="brute",metric="cosine")

In [13]:
model.fit(feature_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [14]:
pivot_table.shape[0]

8225

In [15]:
query_index_row=np.random.choice(pivot_table.shape[0])

In [16]:
query_index_row

2943

In [17]:
query_index_col=np.random.choice(pivot_table.shape[1])

In [18]:
query_index_col

481

In [20]:
distance,index=model.kneighbors(pivot_table.iloc[query_index_row,:].values.reshape(1,-1),n_neighbors=10)

In [21]:
distance,index

(array([[0.        , 0.40532472, 0.43235547, 0.43283307, 0.44299189,
         0.45515913, 0.45826366, 0.46375789, 0.46397786, 0.4669974 ]]),
 array([[2943, 3543, 7009, 4313, 3910, 3292, 1541, 1704, 3930, 6026]],
       dtype=int64))

In [22]:
distance

array([[0.        , 0.40532472, 0.43235547, 0.43283307, 0.44299189,
        0.45515913, 0.45826366, 0.46375789, 0.46397786, 0.4669974 ]])

In [30]:
pivot_table.columns

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            693, 694, 695, 696, 697, 698, 699, 700, 701, 702],
           dtype='int64', name='userId', length=702)

In [31]:
type(pivot_table)

pandas.core.frame.DataFrame