In [1]:
import numpy as np
import pandas as pd


# Story based and title based rec system

# Viswanadh

In [2]:
data=pd.read_csv("tmdb_5000_movies.csv")

In [3]:
data.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
data['overview']=data['overview'].str.lower()

In [5]:
data.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  in the 22nd century, a paraplegic marine is di...  150.437577   
1  captain barbossa, long believed to be dead, ha...  139.082615   
2  a cryptic message from bond’s past sends him o...  107.376788   
3  following the death of district attorney harve...  112.312950   
4  john carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [6]:
data.dropna(inplace=True)

In [7]:
data['original_title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...                   
4773                                      Clerks
4781                                   Dry Spell
4791                                 Tin Can Man
4796                                      Primer
4801                            Shanghai Calling
Name: original_title, Length: 1493, dtype: object

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
C=CountVectorizer(stop_words='english',ngram_range=(1,3))

In [10]:
stories=data['overview']

In [11]:
nlp_matrix=C.fit_transform(data['overview'])

In [12]:
nlp_matrix

<1493x88637 sparse matrix of type '<class 'numpy.int64'>'
	with 119896 stored elements in Compressed Sparse Row format>

In [13]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [14]:
sig=sigmoid_kernel(nlp_matrix,nlp_matrix)

In [15]:
sig

array([[0.76179309, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159889,
        0.76159416],
       [0.76159416, 0.76177888, 0.76159416, ..., 0.76159889, 0.76159416,
        0.76159416],
       [0.76159416, 0.76159416, 0.76191616, ..., 0.76159416, 0.76159416,
        0.76159416],
       ...,
       [0.76159416, 0.76159889, 0.76159416, ..., 0.76179309, 0.76159416,
        0.76159889],
       [0.76159889, 0.76159416, 0.76159416, ..., 0.76159416, 0.76199187,
        0.76159416],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159889, 0.76159416,
        0.76219052]])

In [16]:
sig[0]

array([0.76179309, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159889,
       0.76159416])

In [17]:
indices=data.index

In [18]:
indices

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            4758, 4760, 4765, 4766, 4772, 4773, 4781, 4791, 4796, 4801],
           dtype='int64', length=1493)

In [19]:
df2=pd.DataFrame(nlp_matrix.toarray())

In [20]:
df2

0      1      2      3      4      5      6      7      8      9      \
0         0      0      0      0      0      0      0      0      0      0   
1         0      0      0      0      0      0      0      0      0      0   
2         0      0      0      0      0      0      0      0      0      0   
3         0      0      0      0      0      0      0      0      0      0   
4         0      0      0      0      0      0      0      0      0      0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1488      0      0      0      0      0      0      0      0      0      0   
1489      0      0      0      0      0      0      0      0      0      0   
1490      0      0      0      0      0      0      0      0      0      0   
1491      0      0      0      0      0      0      0      0      0      0   
1492      0      0      0      0      0      0      0      0      0      0   

      ...  88627  88628  88629  88630  88631  88632  88633  88634  88635  \
0     ...      0      0      0      0      0      0      0      0      0   
1     ...      0      0      0      0      0      0      0      0      0   
2     ...      0      0      0      0      0      0      0      0      0   
3     ...      0      0      0      0      0      0      0      0      0   
4     ...      0      0      0      0      0      0      0      0      0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1488  ...      0      0      0      0      0      0      0      0      0   
1489  ...      0      0      0      0      0      0      0      0      0   
1490  ...      0      0      0      0      0      0      0      0      0   
1491  ...      0      0      0      0      0      0      0      0      0   
1492  ...      0      0      0      0      0      0      0      0      0   

      88636  
0         0  
1         0  
2         0  
3         0  
4         0  
...     ...  
1488      0  
1489      0  
1490      0  
1491      0  
1492      0  

[1493 rows x 88637 columns]

In [21]:
df=pd.Series(data.index,data['original_title'])

In [22]:
df

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ... 
Clerks                                      4773
Dry Spell                                   4781
Tin Can Man                                 4791
Primer                                      4796
Shanghai Calling                            4801
Length: 1493, dtype: int64

In [23]:
sig[0]

array([0.76179309, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159889,
       0.76159416])

In [24]:
sig[df['Avatar']]

array([0.76179309, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159889,
       0.76159416])

In [25]:
ans=sorted(list(enumerate(list(sig[df['Avatar']]))),key=lambda x:x[1],reverse=True)

In [26]:
ans[0:11]

[(0, 0.7617930859495988),
 (1243, 0.7616225833184369),
 (447, 0.761613107856559),
 (579, 0.761613107856559),
 (117, 0.7616083700034916),
 (355, 0.7616083700034916),
 (1091, 0.7616083700034916),
 (30, 0.761603632069004),
 (39, 0.761603632069004),
 (61, 0.761603632069004),
 (118, 0.761603632069004)]

In [27]:
for i in ans:
    print(data['original_title'].iloc[i[0]])

Avatar
Apollo 18
Semi-Pro
Aliens vs Predator: Requiem
Men in Black II
The Matrix
E.T. the Extra-Terrestrial
Transformers: Age of Extinction
World War Z
Edge of Tomorrow
Beowulf
Pirates of the Caribbean: The Curse of the Black Pearl
American Gangster
The Expendables 3
Green Zone
xXx
Lone Survivor
Hanna
Ultraviolet
The Last Stand
Ghosts of Mars
In Bruges
Diamonds Are Forever
The Dark Knight Rises
Spider-Man 3
Avengers: Age of Ultron
Quantum of Solace
Captain America: Civil War
Skyfall
Iron Man 3
Terminator Salvation
Iron Man
Tomorrowland
Wreck-It Ralph
Independence Day: Resurgence
The Hunger Games: Mockingjay - Part 2
Warcraft
Mad Max: Fury Road
G-Force
Mission: Impossible - Rogue Nation
Kung Fu Panda 2
Mission: Impossible III
Ghostbusters
Mission: Impossible - Ghost Protocol
The World Is Not Enough
Home
Clash of the Titans
Mission: Impossible II
Oblivion
Star Wars: Episode II - Attack of the Clones
Gravity
The Martian
Casino Royale
Cloud Atlas
The Peanuts Movie
Men in Black
Toy Story 2


In [66]:
def content_based_rec(title,no_of_rec=10):
    stri=" "
    ans=sig[df[title]]
    ans_list=sorted(list(enumerate(list(ans))),key=lambda x:x[1],reverse=True)
    ans_list=ans_list[1:no_of_rec]
    print("The recommendations are as follows:")
    for i in ans_list:
        stri=stri+" "+data['original_title'].iloc[i[0]]+" and \n"
    return stri
        

In [67]:
content_based_rec('World War Z')

The recommendations are as follows:


'  captain america: the first avenger and \n astro boy and \n ong bak 2 and \n jack the giant slayer and \n war horse and \n man of steel and \n winnie the pooh and \n wu ji and \n zambezia and \n'

# Title based_rec system

In [30]:
data['original_title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...                   
4773                                      Clerks
4781                                   Dry Spell
4791                                 Tin Can Man
4796                                      Primer
4801                            Shanghai Calling
Name: original_title, Length: 1493, dtype: object

In [31]:
data['original_title']=data['original_title'].str.lower()

In [32]:
data['original_title']

0                                         avatar
1       pirates of the caribbean: at world's end
2                                        spectre
3                          the dark knight rises
4                                    john carter
                          ...                   
4773                                      clerks
4781                                   dry spell
4791                                 tin can man
4796                                      primer
4801                            shanghai calling
Name: original_title, Length: 1493, dtype: object

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
c2=TfidfVectorizer(stop_words='english',ngram_range=(1,3))

In [35]:
cv_matrix=c2.fit_transform(data['original_title'])

In [36]:
sigs=sigmoid_kernel(cv_matrix,cv_matrix)

In [37]:
sigs

array([[0.76171331, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
        0.76159416],
       [0.76159416, 0.76171331, 0.76159416, ..., 0.76159416, 0.76159416,
        0.76159416],
       [0.76159416, 0.76159416, 0.76171331, ..., 0.76159416, 0.76159416,
        0.76159416],
       ...,
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76171331, 0.76159416,
        0.76159416],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159416, 0.76171331,
        0.76159416],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
        0.76171331]])

In [38]:
sigs[0]

array([0.76171331, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [39]:
sigs[df['Avatar']]

array([0.76171331, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [40]:
ans=sorted(list(enumerate(list(sigs[df['Avatar']]))),key=lambda x:x[1],reverse=True)

In [41]:
ans

[(0, 0.7617133056681993),
 (1, 0.7615941559557649),
 (2, 0.7615941559557649),
 (3, 0.7615941559557649),
 (4, 0.7615941559557649),
 (5, 0.7615941559557649),
 (6, 0.7615941559557649),
 (7, 0.7615941559557649),
 (8, 0.7615941559557649),
 (9, 0.7615941559557649),
 (10, 0.7615941559557649),
 (11, 0.7615941559557649),
 (12, 0.7615941559557649),
 (13, 0.7615941559557649),
 (14, 0.7615941559557649),
 (15, 0.7615941559557649),
 (16, 0.7615941559557649),
 (17, 0.7615941559557649),
 (18, 0.7615941559557649),
 (19, 0.7615941559557649),
 (20, 0.7615941559557649),
 (21, 0.7615941559557649),
 (22, 0.7615941559557649),
 (23, 0.7615941559557649),
 (24, 0.7615941559557649),
 (25, 0.7615941559557649),
 (26, 0.7615941559557649),
 (27, 0.7615941559557649),
 (28, 0.7615941559557649),
 (29, 0.7615941559557649),
 (30, 0.7615941559557649),
 (31, 0.7615941559557649),
 (32, 0.7615941559557649),
 (33, 0.7615941559557649),
 (34, 0.7615941559557649),
 (35, 0.7615941559557649),
 (36, 0.7615941559557649),
 (37, 0.761

In [42]:
for i in ans:
    print(data['original_title'].iloc[i[0]])

avatar
pirates of the caribbean: at world's end
spectre
the dark knight rises
john carter
spider-man 3
tangled
avengers: age of ultron
harry potter and the half-blood prince
batman v superman: dawn of justice
quantum of solace
pirates of the caribbean: dead man's chest
the lone ranger
man of steel
the avengers
pirates of the caribbean: on stranger tides
men in black 3
the hobbit: the battle of the five armies
the amazing spider-man
robin hood
the hobbit: the desolation of smaug
the golden compass
titanic
captain america: civil war
jurassic world
skyfall
spider-man 2
iron man 3
alice in wonderland
transformers: revenge of the fallen
transformers: age of extinction
oz: the great and powerful
the amazing spider-man 2
tron: legacy
cars 2
green lantern
toy story 3
terminator salvation
furious 7
world war z
x-men: days of future past
jack the giant slayer
prince of persia: the sands of time
pacific rim
transformers: dark of the moon
indiana jones and the kingdom of the crystal skull
the good

In [69]:
def title_rec(title,no_of_rec=10):
    str=" "
    anz=sigs[df[title]]
    ans=sorted(list(enumerate(list(anz))),key=lambda x:x[1],reverse=True)
    ans_list=ans[1:11]
    print("The recommendations are")
    for i in ans_list:
        str=str+data['original_title'].iloc[i[0]]
        
    
    

In [52]:
title_rec('Tangled')

The recommendations are


In [53]:
!pip install gradio

In [70]:
import gradio as gr

In [77]:
iface=gr.Interface(fn=content_based_rec,inputs=["text"],outputs="text",description="Enter a title")
iface.launch(share=True)

TypeError: launch() got an unexpected keyword argument 'inline_css'

The recommendations are as follows:
